debug: true
debugtoadmins: true
saveinterval: 17
DatabaseType: SQLite
MySQL: {}
SQLite:
    Filename: "PlayerDatabase"
worldprotection:
 blockbreak_allowed_in:
    - world_thelab
    - murder
 blockplace_allowed_in:
    - world_thelab
    - murder
 rightclickblock_allowed_in:
    - world_thelab
    - murder