name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
api-version: 1.16

main: ${mainClass}
depend: [Train_Carts,PlaceholderAPI]

commands:
    example:
        description: An example command
        permission: spigotplugin.example
        usage: /<command>
    sit:
        description: plunk that butt down on the ground
        permission: parkmanager.sit
        usage: /<command>
    hideiteminfo:
        description: hides all the flags on the item in hand.
        permission: parkmanager.hideiteminfo
        usage: /<command>
    bench:
        description: Makes a bench at your position
        permission: parkmanager.bench
        usage: /<command>
    modeldata:
        description: edits the data of the item in hand.
        permission: parkmanager.modeldata
        usage: /<command>
    voucher:
        description: edits the data of the item in hand.
        permission: parkmanager.voucher
        usage: /<command>
    rides:
        description: gives the player a list of available rides.
        permission: parkmanager.command.rides
        usage: /<command>
    rideadmin:
        description: management command for rides.
        permission: parkmanager.command.rideadmin
        aliases: [pmra,pmrideadmin]
        usage: /<command>
    exitride:
        description: leave your current ride.
        permission: parkmanager.command.exitride
        aliases: [exit,leaveride]
        usage: /<command>
    resourcepack:
        description: put on the resourcepack!
        aliases: [rp]
        usage: /<command>
    gadgets:
        description: open the gadgets menu!
        aliases: [gadget,cosmetics,trails,hats]
        usage: /<command>

permissions: {}