name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
api-version: 1.16

main: ${mainClass}
depend: [Train_Carts,PlaceholderAPI,Citizens]
softdepend: [ccRides, ViaVersion, ViaBackwards, ViaRewind]

commands:
    sit:
        description: plunk that butt down on the ground
        permission: parkmanager.sit
        usage: /<command>
    hideiteminfo:
        description: hides all the flags on the item in hand.
        permission: parkmanager.command.hideiteminfo
        usage: /<command>
    oweditems:
        description: Gives the player all the items they are owed.
        permission: parkmanager.command.oweditems
        usage: /<command>
    bench:
        description: Makes a bench at your position
        permission: parkmanager.command.bench
        usage: /<command>
    modeldata:
        description: edits the data of the item in hand.
        permission: parkmanager.command.modeldata
        usage: /<command>
    alias:
        description: creates and modifies aliases.
        permission: parkmanager.command.alias
        usage: /<command>
    rides:
        description: gives the player a list of available rides.
        permission: parkmanager.command.rides
        usage: /<command>
    rideadmin:
        description: management command for rides.
        permission: parkmanager.command.rideadmin
        aliases: [pmra,pmrideadmin]
        usage: /<command>
    exitride:
        description: leave your current ride.
        permission: parkmanager.command.exitride
        aliases: [exit,leaveride]
        usage: /<command>
    resourcepack:
        description: put on the resourcepack!
        aliases: [rp]
        usage: /<command>
    gadgets:
        description: open the gadgets menu!
        aliases: [gadget,cosmetics,trails,hats]
        usage: /<command>
    randomride:
        description: takes you to a random ride!
        aliases: [rr]
        usage: /<command>
        permission: parkmanager.command.randomride
    tradingcardadmin:
        description: admin related command for tradingcard.
        aliases: []
        permission: parkmanager.tradingcard.admin
        usage: /<command> argument
    tradingcardevaluate:
        description: evaluates a tradingcard.
        aliases: [evaluatecard]
        permission: parkmanager.tradingcard.admin
        usage: /<command>
    tradingcardsign:
        description: signs a tradingcard.
        aliases: [signcard]
        permission: parkmanager.command.signcard
        usage: /<command>
    tradingcardbinder:
        description: Opens your binder.
        aliases: [binder,cardbinder]
        permission: parkmanager.command.binder
        usage: /<command>
    spawn:
        description: Takes you to spawn.
        permission: parkmanager.command.spawn
        aliases: []
        usage: /<command>
    parkmanager:
        description: Default admin command.
        aliases: []
        permission: parkmanager.admin
        usage: /<command>

permissions: {}