name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
api-version: 1.16

main: ${mainClass}
depend: [Train_Carts,PlaceholderAPI,Citizens]
softdepend: [ccRides, ViaVersion, ViaBackwards, ViaRewind]

commands:
    sit:
        description: plunk that butt down on the ground
        permission: parkmanager.sit
        usage: /<command>
    granttag:
        description: Grant a deluxetag to a player.
        permission: parkmanager.command.granttag
        usage: /granttag <name> <tag>
    hideiteminfo:
        description: hides all the flags on the item in hand.
        permission: parkmanager.command.hideiteminfo
        usage: /<command>
    oweditems:
        description: Gives the player all the items they are owed.
        permission: parkmanager.command.oweditems
        usage: /<command>
    bench:
        description: Makes a bench at your position
        permission: parkmanager.command.bench
        usage: /<command>
    modeldata:
        description: edits the data of the item in hand.
        permission: parkmanager.command.modeldata
        usage: /<command>
    alias:
        description: creates and modifies aliases.
        permission: parkmanager.command.alias
        usage: /<command>
    rides:
        description: gives the player a list of available rides.
        permission: parkmanager.command.rides
        usage: /<command>
    rideadmin:
        description: management command for rides.
        permission: parkmanager.command.rideadmin
        aliases: [pmra,pmrideadmin]
        usage: /<command>
    exitride:
        description: leave your current ride.
        permission: parkmanager.command.exitride
        aliases: [exit,leaveride]
        usage: /<command>
    resourcepack:
        description: put on the resourcepack!
        aliases: [rp]
        usage: /<command>
    randomride:
        description: takes you to a random ride!
        aliases: [rr]
        usage: /<command>
        permission: parkmanager.command.randomride
    tradingcardadmin:
        description: admin related command for tradingcard.
        aliases: []
        permission: parkmanager.admin
        usage: /<command> argument
    tradingcardevaluate:
        description: evaluates a tradingcard.
        aliases: [evaluatecard]
        permission: parkmanager.admin
        usage: /<command>
    tradingcardsign:
        description: signs a tradingcard.
        aliases: [signcard]
        permission: parkmanager.command.signcard
        usage: /<command>
    tradingcardbinder:
        description: Opens your binder.
        aliases: [binder,cardbinder]
        permission: parkmanager.command.binder
        usage: /<command>
    spawn:
        description: Takes you to spawn.
        permission: parkmanager.command.spawn
        aliases: []
        usage: /<command>
    namecolor:
        description: Allows you to change your namecolor, using essentials.
        permission: parkmanager.command.namecolor
        aliases: []
        usage: /<command> (color)
    parkmanager:
        description: Default admin command.
        aliases: []
        permission: parkmanager.admin
        usage: /<command>
    forcehat:
        description: Forces the item in hand to be your hat.
        aliases: []
        permission: parkmanager.command.forcehat
        usage: /<command>
    adminwarp:
        description: Warp to adminwarps.
        aliases: []
        permission: parkmanager.command.adminwarp
        usage: /<command>
    setadminwarp:
        description: set adminwarps.
        aliases: []
        permission: parkmanager.command.setadminwarp
        usage: /<command>
    deladminwarp:
        description: set adminwarps.
        aliases: []
        permission: parkmanager.command.deladminwarp
        usage: /<command>
permissions:
    parkmanager.sit:
        description: "Permission to use the /sit command."
        default: op
    parkmanager.command.granttag:
        description: "Permission to grant tags to players."
        default: op    
    parkmanager.command.namecolor:
        description: "Permission to use the /namecolor command."
        default: op
    parkmanager.command.rides:
        descrption: "Permission to use the /rides command."
        default: true
    parkmanager.command.signcard:
        descrption: "Permission to use the /signcard command."
        default: true
    parkmanager.command.binder:
        descrption: "Permission to use the /binder command."
        default: true
    parkmanager.command.spawn:
        descrption: "Permission to use the /spawn command."
        default: true
    parkmanager.command.oweditems:
        descrption: "Permission to use the /oweditems command."
        default: true
    parkmanager.command.exitride:
        descrption: "Permission to use the /exitride command."
        default: true
    parkmanager.command.randomride:
        descrption: "Permission to use the /randomride command."
        default: true   
    parkmanager.command.bench:
        descrption: "Permission to use the /bench command."
        default: op
    parkmanager.command.adminwarp:
        descrption: "Permission to use the /adminwarp command."
        default: op
    parkmanager.command.setadminwarp:
        descrption: "Permission to use the /adminwarp command."
        default: op
    parkmanager.command.deladminwarp:
        descrption: "Permission to use the /adminwarp command."
        default: op
    parkmanager.command.modeldata:
        descrption: "Permission to use the /modeldata command."
        default: op 
    parkmanager.command.forcehat:
        descrption: "Permission to use the /forcehat command."
        default: op
    parkmanager.command.hideiteminfo:
        descrption: "Permission to use the /hideiteminfo command."
        default: op
    parkmanager.command.rideadmin:
        descrption: "Permission to use the /rideadmin command."
        default: op
    parkmanager.command.alias:
        descrption: "Permission to use the /alias command."
        default: op
    parkmanager.admin:
        descrption: "Permission to use the /parkmanager command and other admin related commands."
        default: op
    parkmanager.tradingcard.admin:
        descrption: "Outdated permission."
        default: false